from __future__ import annotations

TACTIC_SEEDS = [
    {
        "id": "T001",
        "name": "反手挡网",
        "content": "当对手重杀深入你的场地时，用轻柔的反手挡网迫使对手上前。",
        "tag": "defense",
        "style_family": "absorb-and-redirect",
        "tempo_band": "fast",
        "phase_preference": "under_pressure",
        "preferred_last_hitter": "OPPONENT",
        "applicable_events": ["重力杀球", "陡压杀球", "Smash", "压力回合"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 90,
        "speed_max": 260,
        "court_contexts": ["rear_channel", "rear_wide", "mid_channel"],
        "risk_level": "medium",
        "recovery_cost": 0.46,
        "pressure_gain": 0.84,
    },
    {
        "id": "T002",
        "name": "深区挑球重置",
        "content": "当对手站位过前时，快速挑球到后场角落重置回合。",
        "tag": "attack",
        "style_family": "reset-and-rebuild",
        "tempo_band": "medium",
        "phase_preference": "neutral",
        "preferred_last_hitter": "USER",
        "applicable_events": ["压力回合", "抽球交换", "控制回合"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 40,
        "speed_max": 180,
        "court_contexts": ["front_central", "mid_central", "front_channel"],
        "risk_level": "low",
        "recovery_cost": 0.34,
        "pressure_gain": 0.58,
    },
    {
        "id": "T003",
        "name": "斜线放网结束",
        "content": "网前旋转质量高时，保持前压并准备惩罚对手松动的对角回球。",
        "tag": "net",
        "style_family": "front-court-trap",
        "tempo_band": "controlled",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["控制回合", "压力回合", "网前控制"],
        "preferred_match_types": ["singles"],
        "speed_min": 25,
        "speed_max": 120,
        "court_contexts": ["front_central", "front_channel"],
        "risk_level": "medium",
        "recovery_cost": 0.42,
        "pressure_gain": 0.79,
    },
    {
        "id": "T004",
        "name": "直线解围高远",
        "content": "在被动反手过渡时，打直线高远球降低被截风险。",
        "tag": "defense",
        "style_family": "reset-and-rebuild",
        "tempo_band": "medium",
        "phase_preference": "under_pressure",
        "preferred_last_hitter": "OPPONENT",
        "applicable_events": ["压力回合", "抽球交换", "Smash"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 55,
        "speed_max": 170,
        "court_contexts": ["mid_wide", "rear_wide", "mid_channel"],
        "risk_level": "low",
        "recovery_cost": 0.28,
        "pressure_gain": 0.49,
    },
    {
        "id": "T005",
        "name": "四角拉开消耗",
        "content": "当对手体能下降时，将球拉开到四个角落消耗其体力。",
        "tag": "tactic",
        "style_family": "attritional-pressure",
        "tempo_band": "controlled",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["控制回合", "压力回合"],
        "preferred_match_types": ["singles"],
        "speed_min": 20,
        "speed_max": 130,
        "court_contexts": ["mid_central", "rear_central", "mid_channel"],
        "risk_level": "medium",
        "recovery_cost": 0.52,
        "pressure_gain": 0.82,
    },
    {
        "id": "T006",
        "name": "身体抽球压迫",
        "content": "平抽交换中，向对手右肩方向用力抽球，压缩其击球空间迫使弱回。",
        "tag": "attack",
        "style_family": "compression-attack",
        "tempo_band": "fast",
        "phase_preference": "neutral",
        "preferred_last_hitter": "USER",
        "applicable_events": ["抽球交换", "压力回合"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 85,
        "speed_max": 210,
        "court_contexts": ["mid_central", "mid_channel", "front_central"],
        "risk_level": "medium",
        "recovery_cost": 0.55,
        "pressure_gain": 0.88,
    },
    {
        "id": "T007",
        "name": "后场假动作弹指",
        "content": "从后场做出直线放网动作，然后突然弹指越过对手破坏其节奏。",
        "tag": "attack",
        "style_family": "deception",
        "tempo_band": "medium",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["控制回合", "压力回合", "陡压杀球"],
        "preferred_match_types": ["singles"],
        "speed_min": 60,
        "speed_max": 170,
        "court_contexts": ["rear_central", "rear_channel"],
        "risk_level": "high",
        "recovery_cost": 0.61,
        "pressure_gain": 0.9,
    },
    {
        "id": "T008",
        "name": "接发网前封压",
        "content": "短发或轻柔开局后，贴网封压不让对手舒适地起球。",
        "tag": "net",
        "style_family": "front-court-trap",
        "tempo_band": "controlled",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["网前控制", "控制回合"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 10,
        "speed_max": 90,
        "court_contexts": ["front_central", "front_wide", "front_channel"],
        "risk_level": "low",
        "recovery_cost": 0.25,
        "pressure_gain": 0.76,
    },
    {
        "id": "T009",
        "name": "中场截击扫压",
        "content": "在下一个平球时主动上前，在身体前方提前截击，在回合重置前切断局面。",
        "tag": "attack",
        "style_family": "interception",
        "tempo_band": "fast",
        "phase_preference": "transition",
        "preferred_last_hitter": "OPPONENT",
        "applicable_events": ["抽球交换", "压力回合", "快速平抽交换"],
        "preferred_match_types": ["doubles", "singles"],
        "speed_min": 95,
        "speed_max": 230,
        "court_contexts": ["mid_central", "mid_channel", "front_channel"],
        "risk_level": "high",
        "recovery_cost": 0.66,
        "pressure_gain": 0.93,
    },
    {
        "id": "T010",
        "name": "应急半杀",
        "content": "无法充分起跳时，用陡压半杀攻向身体保持进攻，避免重心过度前压。",
        "tag": "tactic",
        "style_family": "managed-pressure",
        "tempo_band": "medium-fast",
        "phase_preference": "transition",
        "preferred_last_hitter": "USER",
        "applicable_events": ["压力回合", "控制回合", "陡压杀球"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 70,
        "speed_max": 185,
        "court_contexts": ["rear_central", "rear_channel", "mid_central"],
        "risk_level": "medium",
        "recovery_cost": 0.44,
        "pressure_gain": 0.74,
    },
]

TT_TACTIC_SEEDS = [
    {
        "id": "TT001",
        "name": "正手弧圈拉球",
        "content": "当对手长推到你的正手位时，侧身绕步用强烈上旋拉到对方反手位抢先。",
        "tag": "attack",
        "style_family": "topspin-attack",
        "tempo_band": "fast",
        "phase_preference": "neutral",
        "preferred_last_hitter": "USER",
        "applicable_events": ["多拍相持", "发球抢攻", "快攻得分"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 50,
        "speed_max": 120,
        "court_contexts": ["A_deep_channel", "A_mid_central", "B_deep_channel"],
        "risk_level": "medium",
        "recovery_cost": 0.48,
        "pressure_gain": 0.86,
    },
    {
        "id": "TT002",
        "name": "反手香蕉弧拧",
        "content": "对方反手位短下旋发球时，用手腕发力的香蕉弧拧带侧旋将球拐向对方正手大角。",
        "tag": "attack",
        "style_family": "deception",
        "tempo_band": "fast",
        "phase_preference": "neutral",
        "preferred_last_hitter": "OPPONENT",
        "applicable_events": ["发球抢攻", "短球控制"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 35,
        "speed_max": 95,
        "court_contexts": ["A_net_central", "A_net_channel", "B_net_central"],
        "risk_level": "high",
        "recovery_cost": 0.58,
        "pressure_gain": 0.91,
    },
    {
        "id": "TT003",
        "name": "短推控制",
        "content": "用轻柔触感保持球低平过网并落在近网区，阻止对手先手进攻。适合化解强发球。",
        "tag": "control",
        "style_family": "short-game",
        "tempo_band": "controlled",
        "phase_preference": "neutral",
        "preferred_last_hitter": "OPPONENT",
        "applicable_events": ["短球控制", "多拍相持"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 10,
        "speed_max": 50,
        "court_contexts": ["A_net_central", "A_net_channel", "B_net_central"],
        "risk_level": "low",
        "recovery_cost": 0.22,
        "pressure_gain": 0.55,
    },
    {
        "id": "TT004",
        "name": "快速直线进攻",
        "content": "当回球偏高或半出台时，平快地沿直线打向对方身体或手肘位置压迫其出手。",
        "tag": "attack",
        "style_family": "compression-attack",
        "tempo_band": "fast",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["快攻得分", "发球抢攻", "多拍相持"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 65,
        "speed_max": 130,
        "court_contexts": ["A_mid_central", "B_mid_central", "A_deep_central"],
        "risk_level": "medium",
        "recovery_cost": 0.50,
        "pressure_gain": 0.88,
    },
    {
        "id": "TT005",
        "name": "强侧旋发球",
        "content": "用摆式发球带强烈侧旋和低弧线，将对手拉开并为第三板进攻创造空间。",
        "tag": "serve",
        "style_family": "serve-variation",
        "tempo_band": "controlled",
        "phase_preference": "neutral",
        "preferred_last_hitter": "USER",
        "applicable_events": ["发球抢攻", "短球控制"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 15,
        "speed_max": 60,
        "court_contexts": ["A_net_wide", "A_net_channel", "B_net_wide"],
        "risk_level": "low",
        "recovery_cost": 0.20,
        "pressure_gain": 0.72,
    },
    {
        "id": "TT006",
        "name": "下旋削球防守",
        "content": "面对强烈上旋拉球，后退用重下旋削球降低节奏，迫使对手重新开局。",
        "tag": "defense",
        "style_family": "absorb-and-redirect",
        "tempo_band": "medium",
        "phase_preference": "under_pressure",
        "preferred_last_hitter": "OPPONENT",
        "applicable_events": ["多拍相持", "快攻得分"],
        "preferred_match_types": ["singles"],
        "speed_min": 30,
        "speed_max": 90,
        "court_contexts": ["A_deep_wide", "A_deep_central", "A_deep_channel"],
        "risk_level": "medium",
        "recovery_cost": 0.40,
        "pressure_gain": 0.60,
    },
    {
        "id": "TT007",
        "name": "反拉相持",
        "content": "在上旋相持中，贴台用时机反拉改变旋转方向和角度。",
        "tag": "attack",
        "style_family": "topspin-attack",
        "tempo_band": "fast",
        "phase_preference": "neutral",
        "preferred_last_hitter": "OPPONENT",
        "applicable_events": ["多拍相持", "快攻得分"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 55,
        "speed_max": 115,
        "court_contexts": ["A_mid_central", "A_mid_channel", "B_mid_central"],
        "risk_level": "medium",
        "recovery_cost": 0.52,
        "pressure_gain": 0.82,
    },
    {
        "id": "TT008",
        "name": "大角度落点",
        "content": "在正手大角和反手大角之间交替深区落点，拉开对手并在中路创造空档。",
        "tag": "tactic",
        "style_family": "attritional-pressure",
        "tempo_band": "medium",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["多拍相持", "短球控制"],
        "preferred_match_types": ["singles"],
        "speed_min": 35,
        "speed_max": 100,
        "court_contexts": ["A_deep_wide", "B_deep_wide", "A_mid_wide"],
        "risk_level": "low",
        "recovery_cost": 0.35,
        "pressure_gain": 0.78,
    },
    {
        "id": "TT009",
        "name": "身体攻击压迫",
        "content": "将快速平球打向对手手肘交叉点，限制其挥拍空间迫使弱回。",
        "tag": "attack",
        "style_family": "compression-attack",
        "tempo_band": "fast",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["快攻得分", "多拍相持", "发球抢攻"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 60,
        "speed_max": 125,
        "court_contexts": ["A_mid_central", "B_mid_central"],
        "risk_level": "medium",
        "recovery_cost": 0.46,
        "pressure_gain": 0.85,
    },
    {
        "id": "TT010",
        "name": "轻触放短",
        "content": "当对手远离球台时，用精巧的放短球带微下旋刚好过网直接得分。",
        "tag": "control",
        "style_family": "short-game",
        "tempo_band": "controlled",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["短球控制", "多拍相持"],
        "preferred_match_types": ["singles"],
        "speed_min": 5,
        "speed_max": 35,
        "court_contexts": ["A_net_central", "A_net_channel", "B_net_central"],
        "risk_level": "high",
        "recovery_cost": 0.30,
        "pressure_gain": 0.80,
    },
]

ALL_TACTIC_SEEDS = TACTIC_SEEDS + TT_TACTIC_SEEDS
TACTIC_NAME_BY_ID = {seed["id"]: seed["name"] for seed in ALL_TACTIC_SEEDS}


def get_seeds_for_sport(sport_type: str = "badminton"):
    """Return the tactic seeds applicable to the given sport."""
    if sport_type == "table_tennis":
        return TT_TACTIC_SEEDS
    return TACTIC_SEEDS
